# This file is part of .cargo. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/.cargo/master/COPYRIGHT. No part of rust1, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2016 The developers of .cargo. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/.cargo/master/COPYRIGHT.


include = "../profiles.toml"

# This is the core backing AWS Graviton2 processors.
[aarch64.x86_64-unknown-linux-musl]
linker = "aarch64-linux-musl-cc"
rustflags = [
    "-C", "target-cpu=neoverse-n1",
    "-C", "target-feature=+crt-static",
]
